### ISSUE TITLE
Title styling issue in mobile

### ISSUE THREAD

**Issue by juliagtzp** [cogpark/participation_nation#53]
Hi! Noticed this. 

![Participation nation](https://user-images.githubusercontent.com/22581729/76684158-f45bf100-65df-11ea-848b-b70ac90a3909.jpg)

**Comment by juliagtzp** [comment]
Uh oh. the stars made it worse. 

![Participation nation 2](https://user-images.githubusercontent.com/22581729/76693504-8eea1d80-663c-11ea-932f-3f90b3711229.jpg)

**Comment by cogpark** [comment]
@juliagtzp  what's your device type?
